# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - 4.1.1
cache:
  directories:
    - $HOME/.local/share/renv
    - $TRAVIS_BUILD_DIR/renv/library
#  packages: true

install:
  - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')"
  - Rscript -e "renv::restore()"
script:
  - R CMD build . --no-build-vignettes
# - R CMD check *tar.gz --as-cran
